In [2]:
import cv2
import matplotlib.pyplot as plt
import cvlib as cv
from cvlib.object_detection import draw_bbox

In [3]:
import os
import pandas as pd
import cv2
from Frames import get_frames
from count_objects import count

In [4]:
video = cv2.VideoCapture('Pothole_trial_25.mp4')

In [5]:
get_frames(video)

In [6]:
path = os.getcwd()
ImageDetected = [f for f in os.listdir(path) if f.endswith('.jpg')]

In [7]:
images = ImageDetected

lst = []
for k in images:
    temp = k.split('.')
    first = temp[0]
    lst.append(int(first))

lst.sort()
temp = []
for k in lst:
    temp.append(str(k) + ".jpg")

images = temp

In [8]:
images

['1.jpg',
 '2.jpg',
 '3.jpg',
 '4.jpg',
 '5.jpg',
 '6.jpg',
 '7.jpg',
 '8.jpg',
 '9.jpg',
 '10.jpg',
 '11.jpg',
 '12.jpg',
 '13.jpg',
 '14.jpg',
 '15.jpg',
 '16.jpg',
 '17.jpg',
 '18.jpg',
 '19.jpg',
 '20.jpg',
 '21.jpg',
 '22.jpg',
 '23.jpg',
 '24.jpg',
 '25.jpg',
 '26.jpg',
 '27.jpg',
 '28.jpg',
 '29.jpg',
 '30.jpg',
 '31.jpg',
 '32.jpg',
 '33.jpg',
 '34.jpg',
 '35.jpg',
 '36.jpg',
 '37.jpg',
 '38.jpg',
 '39.jpg',
 '40.jpg',
 '41.jpg',
 '42.jpg',
 '43.jpg',
 '44.jpg',
 '45.jpg',
 '46.jpg',
 '47.jpg',
 '48.jpg',
 '49.jpg',
 '50.jpg',
 '51.jpg',
 '52.jpg',
 '53.jpg',
 '54.jpg',
 '55.jpg',
 '56.jpg',
 '57.jpg',
 '58.jpg',
 '59.jpg',
 '60.jpg',
 '61.jpg',
 '62.jpg',
 '63.jpg',
 '64.jpg',
 '65.jpg',
 '66.jpg',
 '67.jpg',
 '68.jpg',
 '69.jpg',
 '70.jpg',
 '71.jpg',
 '72.jpg',
 '73.jpg']

In [9]:
count_car = []
count_person = []
count_motorcycle = []
count_truck = []
#list
for i in range(len(images)):
    a, b, c, d = count(images[i])
    count_car.append(a)
    count_person.append(b)
    count_motorcycle.append(c)
    count_truck.append(d)

In [10]:
print(count_car)
print(count_person)
print(count_motorcycle)
print(count_truck)

['0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1', '2', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
['2', '1', '1', '2', '2', '1', '1', '1', '2', '0', '0', '1', '1', '1', '3', '5', '4', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '1', '0', '1', '1', '0', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '0', '1', '1', '1', '2', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0']
['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '2', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']
['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0']

In [11]:
df = pd.read_csv('25-Sep.csv')
df.shape

(104, 84)

In [12]:

df.shape[0]

104

In [13]:
df['Speed (OBD)(km/h)'].tail()

99     0
100    0
101    0
102    0
103    0
Name: Speed (OBD)(km/h), dtype: int64

In [17]:
len(df['Speed (OBD)(km/h)'])

104

In [14]:
df=df[df['Trip Time(Since journey start)(s)']>0]

df.shape

(85, 84)

In [15]:
Time = df['Trip Time(Since journey start)(s)'][:73]
Speed = df['Speed (OBD)(km/h)'][:73]
Latitude = df[' Latitude'][:73]
Longitude = df[' Longitude'][:73]
len(Time)

73

In [16]:
count_car = count_car
count_person = count_person
count_motorcycle = count_motorcycle
count_truck = count_truck
len(count_car)

73

In [17]:
# 'TIME': Time, 'SPEED': Speed, 
Dict = {'TIME': Time, 'SPEED': Speed, 'Latitude':Latitude, 'Longitude':Longitude , 'CARS': count_car, 'PERSONS': count_person, 'MOTORCYCLES': count_motorcycle, 'TRUCKS': count_truck}
Dict

{'TIME': 19     1
 20     2
 21     3
 22     4
 23     5
       ..
 87    69
 88    70
 89    71
 90    72
 91    73
 Name: Trip Time(Since journey start)(s), Length: 73, dtype: int64,
 'SPEED': 19    4
 20    7
 21    7
 22    7
 23    7
      ..
 87    5
 88    1
 89    0
 90    0
 91    0
 Name: Speed (OBD)(km/h), Length: 73, dtype: int64,
 'Latitude': 19    18.630658
 20    18.630658
 21    18.630658
 22    18.630658
 23    18.630658
         ...
 87    18.630295
 88    18.630295
 89    18.630295
 90    18.630295
 91    18.630295
 Name:  Latitude, Length: 73, dtype: float64,
 'Longitude': 19    73.789709
 20    73.789709
 21    73.789709
 22    73.789709
 23    73.789709
         ...
 87    73.792155
 88    73.792155
 89    73.792155
 90    73.792155
 91    73.792155
 Name:  Longitude, Length: 73, dtype: float64,
 'CARS': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '1',
  '2',
  '1',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '1',
  '1',
  '1',
  '0',
  '1',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'PERSONS': ['2',
  '1',
  '1',
  '2',
  '2',
  '1',
  '1',
  '1',
  '2',
  '0',
  '0',
  '1',
  '1',
  '1',
  '3',
  '5',
  '4',
  '0',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '1',
  '1',
  '0',
  '0',
  '0',
  '0',
  '1',
  '0',
  '1',
  '1',
  '0',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '1',
  '0',
  '1',
  '1',
  '1',
  '2',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'MOTORCYCLES': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '2',
  '1',
  '1',
  '1',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'TRUCKS': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '1',
  '1',
  '1',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0']}

In [18]:
Data = pd.DataFrame(Dict)
Data

    TIME  SPEED   Latitude  Longitude CARS PERSONS MOTORCYCLES TRUCKS
19     1      4  18.630658  73.789709    0       2           0      0
20     2      7  18.630658  73.789709    0       1           0      0
21     3      7  18.630658  73.789709    0       1           0      0
22     4      7  18.630658  73.789709    0       2           0      0
23     5      7  18.630658  73.789709    0       2           0      0
..   ...    ...        ...        ...  ...     ...         ...    ...
87    69      5  18.630295  73.792155    0       0           0      0
88    70      1  18.630295  73.792155    0       0           0      0
89    71      0  18.630295  73.792155    0       0           0      0
90    72      0  18.630295  73.792155    0       0           0      0
91    73      0  18.630295  73.792155    0       0           0      0

[73 rows x 8 columns]

In [19]:
Data.to_csv('firstop.csv')